Update RD2 preflight class_path to work-around installer errors (#7198)
A recent change to CumulusCI resulted in a regression for certain custom
tasks. Before this commit:

```console
$ cci task run is_rd2_enabled
Error: module 'tasks' has no attribute 'is_rd2_enabled'

Run this command for more information about debugging errors: cci error --help
```

This resulted in an error when running preflight checks for the
`enhanced-recurring-donations` plan in MetaDeploy. After:

```console
$ cci task run is_rd2_enabled
is_rd2_enabled

  Description: This preflight check ensures that Enhanced Recurring Donations is enabled

  Class: tasks.check_rd2_enablement.is_rd2_enabled
[...]
```

Co-authored-by: James Estevez <jestevez@salesforce.com>