Feature/bge integration (#3215)
* separate filter groups for soft credits

* updated tests

* Fix use of namespace prefix in the CRLP Setup

* added logic for fix the bug into afterInitHandler() method

* UX Updates

* fixed group static names

* if no dev name is found for a RT ID, ditch it

* Be sure to allow the CustomizableRollupSettings default record to be created during the package install. Otherwise found that the next time this was referenced was by the scheduled batch jobs at night, all of which attempted to insert the default record at the same time causing an error.

* Update CRLP_DefaultConfigBuilder_SVC.cls

Removing isActive filter on record type query.

* UX updates

* Updates to dryrun logic

* Update to button logic

* Removing files from DEV REPO

* Remove the default RT name from the logic to convert excluded RT Id's into developer names.

* Added missed metadata  in package.xml
delete POC

* By using the dispatcher, Skew Mode limitations have been greatly reduced. As a result, this fail-safe of writing to the parent object every 200 skipped batch iterations is no longer necessary. As a result, the value has been significantly increased to continue to act as a fail-safe, but at a level that is well beyond what should be reasonable for skew mode batch jobs.

* Caching in LEX has been a nightmare for UI testing in scratch orgs. This change disables the `Enable secure and persistent browser caching to improve performance` option in Session Settings when the scratch org is provisioned.

* Retrieve data update

* Updating package xml

* update metadata batch template

* update metadata import batch

* Fixing with Nic the branch

* Fixes

* Fix updates

* Fixed headers labels

* Feedback: Layout and Alignment fixes

* Improve padding bottom responsiveness

* Fix updates

* FIXED: Column headers Alignment should match column's content - Text Left Aligned, Quantities Right Aligned

* update metadata import batch

* Updating static resource for testing

* Adding back button to lack of batch.
Multiple error support on client side

* updated assert messages

* Updates to GRID loading and pagination

* Fix to labels

* amount field draws from UDR source field

* Adding label to package xml

* allow for all UDR-potential data types

* re-commit missed components

* commit button fix
update resources

* update bgeResources

* metadata update

* update to rendering, pagination and tooltip display

* add remove metadata in package xml customlabels
remove incorrect reference of button in data import batch layout

* working on date update

* Added action list context in batch template layout

* adding value

* change position of summary data
alignment of header components
make responsive table succesfully

* Fix a new unit test error that popped up in our MetaCI builds due to a potential uniqueness issue with the dummy Username in this test method.

* filter rule shows OCR Role values for PSC Role Name field

* Remove namespacing logic from the UDR target object and field since this is not required and will attempt to add the NPSP namespace to a customer's own custom field

* Change in trigger to fix tests for BDI.

* Fixing date issues

* add percent field support, fixed alphabetization to be case-insensitive

* allow average of a percent

* fix bug "Phone fields, billing street, employees y home street fields no guardan data - NullPointer error in console"

* Moved back to settings link into SVC to bypass need for namespace.

* Added jQuery dropdown to the page, modified app.js to load the dropdown.

* Cell appears bigger in edit mode

* Changed logic to use angular functionality.

* "When in the grid, if you navigate all the way to the left, the scroll is then controlled by the arrow keys" - fixed

* fixed bug: opening the grid, "Missing Template" error appears when spinner is displayed

* Polished code.

* Committing static resources.

* Support for first/last UDR records.

* Updated static resource.

* Fixing RT showing ID

* update static respurce

* Updating recordtype view and alter row functionality

* Made UDR names unique and improved their naming by removing namespacing.

* update to record type id picklist
remove row from action list

* static resource

* re deploy fix in cell edit

* minor layout change

* Fixed "When moving to another page and typing in a cell and leaving it, grid starts to throw "Unable to serialize a map with a null key" in the console."

* Updated Static Resources.

* unreq field

* Add "Amount Not Null" Filter Rule

* Count operation does not ignore null values

* re-commit template creation aura component

* Fixed Next button not being enabled correctly.

* Found that the call to getOrgCustomizableRollupSettings() was only happening during a new package install as opposed to upgrades. Updated the installs script to add a new method to handle upserting any default custom settings records going forward.

* center alignment of action icons
added cancel buttonin Batch Template Creation component
addded edit button in batch tempalte layout
changes  in batch template layout

* Updated to optimal dynamic reference

* Recreated static resource.

* Value field is editable on Filter Rule page layout in Setup

* Removed form factors in action overrides for  Batch Template Object.

* add vertical alginment to action icons
fix 'date is defauting to 11/31/1969' bug

* fix deployment bug

* Skip any invalid UDR on Rollup conversion.

* Add a check on the target field.

* Because CRLP enablement is asynchronous, can't make the call to the submitFeatureTelemetryToLMO() method until the end of the async deployment process.

* Date format is being saved incorrectly. -when refreshing grid format displays correctly but it is not

fixed bug when is displayed date after render

* Date format is being saved incorrectly. -when refreshing grid format displays correctly but it is not

Date is not being edited on data import.

When you type a string in a date field and hit enter, the enter does not moves the selection to the next row, but keeps creating spaces on the field. You can't type in any other field and you need to reload the grid in order to use it again.

* Sanitation of object before being sent to UI interface

* updates to cell date rendering

* static resource update

* Fixing cell manipulation when paginating

* code clean up
fix: Actions column should not make focus on the first cell of the row when you click on the icon

* code clean up
fix: Actions column should not make focus on the first cell of the row when you click on the icon

* Fixed failling test

* FIXED:  Picklist - large string breaks cell height

* Fixed issue: "tooltip not dissapearing when clearing cell value".

* Recreated static resources.

* Adding more values for lookup settings

* Validation to review column is not being lost when clicking on action column

* update to static resource

* Fixed issues where when dragging down an incorrect email field only the first one is flagged as incorrect.

* FIXED: dragging an empty picklist , mark errors in cell

* Fixed "When copy/pasting various fields if one is an incorrect email then no data imports are created."

* Recreated static resource.

* package xml update

* Fixed "forEach is not a function" error.

* Refactored code.

* Removed debug logs, recreated static resource.

* Errors fixed:

Update of ListView Batch_Template__c.All: Error: Not in package.xml

Update of WebLink Contact.Recalculate_Rollups: Error: Not in package.xml

Update of CustomField Batch_Template__c.Donation_Matching_Behavior__c: Error on line 134, col 13: Property 'picklist' not valid in version 39.0

Update of Layout Batch_Template__c-BGE Batch Template Layout: Error on line 91, col 19: In field: relatedList - no CustomField named DataImportBatch__c.Batch_Template__c found

Update of Layout DataImportBatch__c-NPSP Data Import Batch Layout: Error on line 35, col 26: In field: field - no CustomField named DataImportBatch__c.Batch_Template__c found

* Fixes:

Update of CustomField Batch_Template__c.Donation_Matching_Behavior__c: Error on line 134, col 13: Property 'picklist' not valid in version 39.0

* update data import batch object

update package.xml

* fix

Update of CustomField DataImportBatch__c.Donation_Matching_Behavior__c: Error on line 154, col 13: Property 'picklist' not valid in version 39.0

* fixed:

Update of AuraDefinitionBundle BGE_BatchContainer: Error: No EVENT named markup://c:SearchKeyChange found : [markup://c:BGE_BatchContainer, markup://c:BGE_BatchSelection]

Update of AuraDefinitionBundle BGE_BatchSelection: Error: No EVENT named markup://c:SearchKeyChange found : [markup://c:BGE_BatchSelection]

* fixed

Update of None DataImportBatch__c.No_Batch_Template_associated: Error: An object 'DataImportBatch__c.No_Batch_Template_associated' of type ValidationRule was named in package.xml, but was not found in zipped directory